#!/usr/bin/env bash

# Main pre-commit hook - runs all scripts in pre-commit.d/

HOOK_DIR="$(dirname "$0")/pre-commit.d"

if [ -d "$HOOK_DIR" ]; then
  for hook in "$HOOK_DIR"/*.sh; do
    if [ -x "$hook" ]; then
      "$hook"
      exit_code=$?
      if [ $exit_code -ne 0 ]; then
        exit $exit_code
      fi
    fi
  done
fi

exit 0
